# Generated by Django 5.0.7 on 2025-06-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interiordesignapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='HomeContent',
        ),
        migrations.DeleteModel(
            name='JobOpening',
        ),
        migrations.DeleteModel(
            name='ProcessStep',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
