# Generated by Django 5.0.7 on 2025-06-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interiordesignapp', '0002_delete_aboutus_delete_contactmessage_delete_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
