# Generated by Django 5.0.7 on 2025-06-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiordesignapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='images/post_index')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
