# Generated by Django 5.0.7 on 2025-06-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiordesignapp', '0004_postproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('furniture_design', 'Furniture Design'), ('interior_design', 'Interior Design'), ('property_management', 'Property Management'), ('property_remodeling', 'Property Remodeling')], max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
